# Author: Gurumoorthy Mohan
version: '3.7'

x-redash-service: &redash-service
  image: formsflow/redash:10.1.2
  depends_on:
      - redis
  env_file: .env
  restart: always
  networks:
    - forms-flow-network
    
services:
  forms-flow-forms-db:
    container_name: forms-flow-forms-db
    image: mongo:5.0
    restart: always
    hostname: forms-flow-forms-db
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${FORMIO_DB_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${FORMIO_DB_PASSWORD:-changeme}
      MONGO_INITDB_DATABASE: ${FORMIO_DB_NAME:-formio}
    volumes:
      - ./../../forms-flow-forms/mongo_entrypoint/001_user.js:/docker-entrypoint-initdb.d/001_user.js:ro
      - .db/mongo/data:/data/db/ 777
      - .db/mongo/data/log:/var/log/mongodb/ 777
      - .db/mongo/mongod.conf:/etc/mongod.conf:rw
    networks:
      - forms-flow-network

  formsflow-db:
    image: postgres:14
    container_name: formsflow-db
    environment:
      POSTGRES_MULTIPLE_DATABASES: bpm,webapi,analytics,adminapi
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    volumes:
      - .db/postgres:/var/lib/postgresql/data 777
      - ./configuration/docker-postgresql-multiple-databases:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
    restart: always
    networks:
      - forms-flow-network

  forms-flow-forms:
    container_name: forms-flow-forms
    image: gil0109/forms-flow-forms:v5.0.2
    
    # The app will restart until Mongo is listening
    restart: always
    depends_on :
      - formsflow-db
    ports:
      - '3001:3001'
    # The application wants to download things to the local directory
    environment:
      DEBUG: formio:*
      NODE_CONFIG: "{\"mongo\":\"mongodb://${FORMIO_DB_USERNAME:-admin}:${FORMIO_DB_PASSWORD:-changeme}@forms-flow-forms-db:27017/${FORMIO_DB_NAME:-formio}?authMechanism=SCRAM-SHA-1&authSource=admin\"}"
      ROOT_EMAIL: ${FORMIO_ROOT_EMAIL:-admin@example.com}
      ROOT_PASSWORD: ${FORMIO_ROOT_PASSWORD:-changeme}
      # Needed to add localhost to forms-flow-forms
      FORMIO_DOMAIN: ${FORMIO_DEFAULT_PROJECT_URL}
      FORMIO_JWT_SECRET: ${FORMIO_JWT_SECRET:---- change me now ---}
      MULTI_TENANCY_ENABLED: ${MULTI_TENANCY_ENABLED:-false}
    stdin_open: true # -i
    tty: true # -t
    networks:
      - forms-flow-network

  forms-flow-bpm:
    container_name: forms-flow-bpm
    build:
      context: ./../../forms-flow-bpm/
      dockerfile: Dockerfile
    restart: always
    depends_on :
      - formsflow-db
    ports:
      - '8000:8080'
    environment:
      - KEYCLOAK_URL=${KEYCLOAK_URL}
      - KEYCLOAK_URL_REALM=${KEYCLOAK_URL_REALM:-forms-flow-ai}
      - KEYCLOAK_CLIENTID=${KEYCLOAK_BPM_CLIENT_ID:-forms-flow-bpm}
      - KEYCLOAK_CLIENTSECRET=${KEYCLOAK_BPM_CLIENT_SECRET:-e4bdbd25-1467-4f7f-b993-bc4b1944c943}
      - CAMUNDA_JDBC_URL=${CAMUNDA_JDBC_URL:-jdbc:postgresql://formsflow-db:5432/bpm}
      - CAMUNDA_JDBC_USER=${POSTGRES_USER:-postgres}
      - CAMUNDA_JDBC_PASSWORD=${POSTGRES_PASSWORD:-changeme}
      - CAMUNDA_JDBC_DRIVER=${CAMUNDA_JDBC_DRIVER:-org.postgresql.Driver}
      - CAMUNDA_APP_ROOT_LOG_FLAG=${CAMUNDA_APP_ROOT_LOG_FLAG:-error}
      - FORMSFLOW_API_URL=${FORMSFLOW_API_URL}
      - FORMIO_URL=${FORMIO_DEFAULT_PROJECT_URL}
      - FORMIO_ROOT_EMAIL=${FORMIO_ROOT_EMAIL:-admin@example.com}
      - FORMIO_ROOT_PASSWORD=${FORMIO_ROOT_PASSWORD:-changeme}
      - APP_SECURITY_ORIGIN=${APP_SECURITY_ORIGIN:-*}
      - WEBSOCKET_SECURITY_ORIGIN=${WEBSOCKET_SECURITY_ORIGIN}
      - WEBSOCKET_MESSAGE_TYPE=${WEBSOCKET_MESSAGE_TYPE:-TASK_EVENT}
      - WEBSOCKET_ENCRYPT_KEY=${WEBSOCKET_ENCRYPT_KEY:-giert989jkwrgb@DR55}
      - DATA_BUFFER_SIZE=${DATA_BUFFER_SIZE:-2}
      - IDENTITY_PROVIDER_MAX_RESULT_SIZE=${IDENTITY_PROVIDER_MAX_RESULT_SIZE:-250}
      - DATA_ANALYSIS_URL=${DATA_ANALYSIS_URL}
      - CUSTOM_SUBMISSION_URL=${CUSTOM_SUBMISSION_URL}
      - CUSTOM_SUBMISSION_ENABLED=${CUSTOM_SUBMISSION_ENABLED:-false}
      - MULTI_TENANCY_ENABLED=${MULTI_TENANCY_ENABLED:-false}
      - KEYCLOAK_ENABLE_CLIENT_AUTH=${KEYCLOAK_ENABLE_CLIENT_AUTH:-false}
      - KEYCLOAK_WEB_CLIENTID=${KEYCLOAK_WEB_CLIENT_ID:-forms-flow-web}
      - FORMSFLOW_ADMIN_URL=${FORMSFLOW_ADMIN_URL:-}
      - REDIS_HOST=${REDIS_HOST:-localhost}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSCODE=${REDIS_PASSCODE:-changeme}
      - REDIS_ENABLED=${REDIS_ENABLED:-false}

    networks:
      - forms-flow-network

  forms-flow-web:
    container_name: forms-flow-web
    restart: always
    depends_on :
      - forms-flow-webapi
    build:
      context: ./../../forms-flow-web/
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-production}
        - REACT_APP_API_SERVER_URL=${FORMIO_DEFAULT_PROJECT_URL}
        - REACT_APP_API_PROJECT_URL=${FORMIO_DEFAULT_PROJECT_URL}
        - REACT_APP_KEYCLOAK_CLIENT=${KEYCLOAK_WEB_CLIENT_ID:-forms-flow-web}
        - REACT_APP_WEB_BASE_URL=${WEB_API_URL}
        - REACT_APP_BPM_URL=${WEB_BPM_URL}
        - REACT_APP_WEBSOCKET_ENCRYPT_KEY=${WEBSOCKET_ENCRYPT_KEY:-giert989jkwrgb@DR55}
        - REACT_APP_KEYCLOAK_URL_REALM=${KEYCLOAK_URL_REALM:-forms-flow-ai}
        - REACT_APP_KEYCLOAK_URL=${KEYCLOAK_URL}
        - REACT_APP_APPLICATION_NAME=${APPLICATION_NAME:-formsflow.ai}
        - REACT_APP_USER_ACCESS_PERMISSIONS=${USER_ACCESS_PERMISSIONS}
        - REACT_APP_WEB_BASE_CUSTOM_URL=${WEB_BASE_CUSTOM_URL:-}
        - REACT_APP_MULTI_TENANCY_ENABLED=${MULTI_TENANCY_ENABLED:-false}
        - REACT_APP_MT_ADMIN_BASE_URL=${MT_ADMIN_BASE_URL}
        - REACT_APP_MT_ADMIN_BASE_URL_VERSION=${MT_ADMIN_BASE_URL_VERSION}
        - REACT_APP_CUSTOM_SUBMISSION_URL=${CUSTOM_SUBMISSION_URL}
        - REACT_APP_CUSTOM_SUBMISSION_ENABLED=${CUSTOM_SUBMISSION_ENABLED:-false}
        - REACT_APP_DRAFT_ENABLED=${DRAFT_ENABLED:-false}
        - REACT_APP_DRAFT_POLLING_RATE=${DRAFT_POLLING_RATE:-15000}
        - REACT_APP_EXPORT_PDF_ENABLED=${EXPORT_PDF_ENABLED:-false}
        - REACT_APP_DOCUMENT_SERVICE_URL=${DOCUMENT_SERVICE_URL}
    ports:
      - '3000:8080'
    tty: true
    networks:
      - forms-flow-network

  forms-flow-webapi:
    container_name: forms-flow-webapi
    build:
      context: ./../../forms-flow-api/
      dockerfile: Dockerfile
    restart: always
    depends_on :
      - formsflow-db
      - forms-flow-forms
    entrypoint: "/wait-for-service.sh formsflow-db:5432 -s -- ./entrypoint.sh"
    ports:
      - '5000:5000'
    environment:
      INSIGHT_API_KEY: ${INSIGHT_API_KEY}
      INSIGHT_API_URL: ${INSIGHT_API_URL}
      DATABASE_URL: postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-changeme}@formsflow-db:5432/webapi
      BPM_TOKEN_API: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM:-forms-flow-ai}/protocol/openid-connect/token
      BPM_CLIENT_ID: ${KEYCLOAK_BPM_CLIENT_ID:-forms-flow-bpm}
      BPM_CLIENT_SECRET: ${KEYCLOAK_BPM_CLIENT_SECRET:-e4bdbd25-1467-4f7f-b993-bc4b1944c943}
      BPM_API_URL: ${BPM_API_URL}
      FORMSFLOW_API_CORS_ORIGINS: ${FORMSFLOW_API_CORS_ORIGINS:-*}
      JWT_OIDC_WELL_KNOWN_CONFIG: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM:-forms-flow-ai}/.well-known/openid-configuration
      JWT_OIDC_ALGORITHMS: 'RS256'
      JWT_OIDC_JWKS_URI: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM:-forms-flow-ai}/protocol/openid-connect/certs
      JWT_OIDC_ISSUER: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM:-forms-flow-ai}
      JWT_OIDC_AUDIENCE: ${KEYCLOAK_WEB_CLIENT_ID:-forms-flow-web}
      JWT_OIDC_CACHING_ENABLED: 'True'
      JWT_OIDC_JWKS_CACHE_TIMEOUT: 300
      KEYCLOAK_URL: ${KEYCLOAK_URL}
      KEYCLOAK_URL_REALM: ${KEYCLOAK_URL_REALM:-forms-flow-ai}
      WEB_API_BASE_URL: ${FORMSFLOW_API_URL}
      FORMIO_URL: ${FORMIO_DEFAULT_PROJECT_URL}
      FORMIO_ROOT_EMAIL: ${FORMIO_ROOT_EMAIL:-admin@example.com}
      FORMIO_ROOT_PASSWORD: ${FORMIO_ROOT_PASSWORD:-changeme}
      FORMIO_JWT_SECRET: ${FORMIO_JWT_SECRET:---- change me now ---}
      KEYCLOAK_ENABLE_CLIENT_AUTH: ${KEYCLOAK_ENABLE_CLIENT_AUTH:-false}
      MULTI_TENANCY_ENABLED: ${MULTI_TENANCY_ENABLED:-false}
      WEB_BASE_URL: ${WEB_BASE_URL:-null}

    stdin_open: true # -i
    tty: true # -t
    networks:
      - forms-flow-network

  server:
    <<: *redash-service
    command: server
    ports:
      - '7000:5000'
    environment:
      REDASH_WEB_WORKERS: 4
      REDASH_MULTI_ORG: ${REDASH_MULTI_ORG:-false}
  scheduler:
    <<: *redash-service
    command: scheduler
    depends_on:
      - server
  scheduled_worker:
    <<: *redash-service
    command: worker
  adhoc_worker:
    <<: *redash-service
    command: worker
  worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "periodic emails default"
      WORKERS_COUNT: 1
    depends_on:
      - server

  redis:
    image: redis:6-alpine
    restart: always
    networks:
      - forms-flow-network

networks:
  forms-flow-network:
    driver: 'bridge'

  # ffdocuments:

  # forms-flow-documents-api:
  #   container_name: forms-flow-documents-api
  #   build:
  #     context: ./../../forms-flow-documents/
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - '5006:5006'
  #   volumes:
  #     - ffdocuments:/app:rw
  #   environment:
  #     DATABASE_URL: ${FORMSFLOW_API_DB_URL:--ql://postgres:changeme@forms-flow-webapi-db:5432/webapi}
  #     FORMSFLOW_API_CORS_ORIGINS: ${FORMSFLOW_API_CORS_ORIGINS:-*}
  #     JWT_OIDC_WELL_KNOWN_CONFIG: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM:-forms-flow-ai}/.well-known/openid-configuration
  #     JWT_OIDC_JWKS_URI: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM:-forms-flow-ai}/protocol/openid-connect/certs
  #     JWT_OIDC_ISSUER: ${KEYCLOAK_URL}/auth/realms/${KEYCLOAK_URL_REALM:-forms-flow-ai}
  #     JWT_OIDC_AUDIENCE: ${KEYCLOAK_WEB_CLIENT_ID:-forms-flow-web}
  #     JWT_OIDC_CACHING_ENABLED: 'True'
  #     KEYCLOAK_URL: ${KEYCLOAK_URL}
  #     KEYCLOAK_URL_REALM: ${KEYCLOAK_URL_REALM:-forms-flow-ai}
  #     FORMSFLOW_API_URL: ${FORMSFLOW_API_URL}
  #     FORMSFLOW_DOC_API_URL: ${DOCUMENT_SERVICE_URL}
  #     FORMIO_URL: ${FORMIO_DEFAULT_PROJECT_URL}
  #     FORMIO_ROOT_EMAIL: ${FORMIO_ROOT_EMAIL:-admin@example.com}
  #     FORMIO_ROOT_PASSWORD: ${FORMIO_ROOT_PASSWORD:-changeme}
  #     CHROME_DRIVER_PATH: ${CHROME_DRIVER_PATH}
  #     CUSTOM_SUBMISSION_URL: ${CUSTOM_SUBMISSION_URL}
  #     CUSTOM_SUBMISSION_ENABLED: ${CUSTOM_SUBMISSION_ENABLED}
  #     FORMIO_JWT_SECRET: ${FORMIO_JWT_SECRET:---- change me now ---}
  #     MULTI_TENANCY_ENABLED: ${MULTI_TENANCY_ENABLED:-false}
  #     KEYCLOAK_ENABLE_CLIENT_AUTH: ${KEYCLOAK_ENABLE_CLIENT_AUTH:-false}
  #   stdin_open: true # -i
  #   tty: true # -t
  #   networks:
  #     - forms-flow-network
