# Author: Gurumoorthy Mohan, Kurian Benoy
version: "3.7"

x-redash-service: &redash-service
  image: formsflow/redash:10.1.2
  depends_on:
      - forms-flow-analytics-db
      - redis
  env_file: .env
  restart: always
  networks:
    - docker_forms-flow-network

services:
  server:
    <<: *redash-service
    command: server
    ports:
      - '7000:5000'
    environment:
      REDASH_WEB_WORKERS: 4
      REDASH_MULTI_ORG: ${REDASH_MULTI_ORG:-false}
  scheduler:
    <<: *redash-service
    command: scheduler
    depends_on:
      - server
  scheduled_worker:
    <<: *redash-service
    command: worker
  adhoc_worker:
    <<: *redash-service
    command: worker
  worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "periodic emails default"
      WORKERS_COUNT: 1
    depends_on:
      - server

  redis:
    image: redis:6-alpine
    restart: always
    networks:
      - docker_forms-flow-network

  forms-flow-analytics-db:
    image: postgres:14
    container_name: forms-flow-analytics-db
    environment:
      POSTGRES_USER: ${ANALYTICS_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${ANALYTICS_DB_PASSWORD:-changeme}
      POSTGRES_DB: ${ANALYTICS_DB_NAME:-analytics}
    ports:
      - '7432:5432'
    restart: always
    env_file: .env
    volumes:
      - analyticsdb:/var/lib/postgresql/data
    networks:
      - docker_forms-flow-network
  # Uncomment the following to enable redash mail server
  # email:
  #   image: djfarrelly/maildev
  #   ports:
  #     - "1080:80"
  #   restart: unless-stopped
volumes:
  analyticsdb:
networks:
  docker_forms-flow-network:
    external: true
